Repository AtB-AS/mittatb-app, pull requests merged in 2022-03, with the labels that each got.

#2246 fix: use undefined as non-inspectable icon background
  src/screens/Ticketing/Ticket/TicketInfo.tsx
Labels: bug

#2309 chore: Bump to version 1.17
  .env.example
  env/atb/dev/.env
  env/atb/prodstaging/.env
  env/atb/staging/.env
  env/atb/store/.env
  env/nfk/dev/.env
  env/nfk/prodstaging/.env
  env/nfk/staging/.env
  env/nfk/store/.env
  package.json
Labels: 1.17

#2243 feat: Flere e2e-tester for app
  e2e/testSequencer.js
  e2e/tests/myprofile.e2e.ts
  e2e/tests/notes.txt
  e2e/tests/onboarding.e2e.ts
  e2e/tests/tickets.e2e.ts
  e2e/tests/travelsearch.e2e.ts
  e2e/utils/commonHelpers.ts
  e2e/utils/interactionHelpers.ts
  e2e/utils/myprofile.ts
  e2e/utils/onboarding.ts
  e2e/utils/travelsearch.ts
  src/departure-list/section-items/line.tsx
  src/departure-list/section-items/quay-header.tsx
  src/departure-list/section-items/quay-section.tsx
  src/screens/Assistant_v2/ResultItem.tsx
  src/screens/Assistant_v2/Results.tsx
  src/screens/TripDetails/DepartureDetails/index.tsx
  src/screens/TripDetails/Details/index.tsx
  src/screens/TripDetails/components/TripSection.tsx
  src/screens/TripDetails_v2/DepartureDetails/index.tsx
  src/screens/TripDetails_v2/Details/index.tsx
  src/screens/TripDetails_v2/components/TripSection.tsx
Labels: test

#2374 chore: Bump to version 1.18
  .env.example
  env/atb/dev/.env
  env/atb/prodstaging/.env
  env/atb/staging/.env
  env/atb/store/.env
  env/nfk/dev/.env
  env/nfk/prodstaging/.env
  env/nfk/staging/.env
  env/nfk/store/.env
  package.json
Labels: :iphone: 1.18

#2431 fix: hide results from screen reader when search is empty
  src/screens/Assistant/Assistant.tsx
Labels: PI: Reisesøk OTP2, :iphone: 1.17
