Repository AtB-AS/mittatb-app, pull requests merged in 2022-04, with the labels that each got.

#2514 feat: refactor recentTickets
  src/components/sections/link-item.tsx
  src/reference-data/types.ts
  src/screens/Ticketing/Tickets/RecentTickets/NewRecentTickets.tsx
  src/screens/Ticketing/Tickets/RecentTickets/RecentTicketComponent.tsx
  src/screens/Ticketing/Tickets/RecentTickets/RecentTicketsScrollView.tsx
  src/translations/screens/subscreens/RecentTicketsTexts.ts
Labels: PI: Billettering v2 app

#2550 Fix QA comments on Feedback component
  src/components/feedback/index.tsx
Labels: PI: Innhøsting feedback

#2476 feat: added nfk specific text for ticket splash screen
  src/translations/screens/TicketSplash.ts
Labels: :memo: OOS

#2559 fix: added text for feedback in onboarding for nfk
  src/translations/screens/Onboarding.ts
Labels: :memo: OOS

#2583 chore: Allow release from release/* branch
  tools/release/release-draft.sh
Labels: :wrench: Forvaltning
