Repository AtB-AS/mittatb-app, pull requests merged in 2022-02, with the labels that each got.

#2130 fix: quay section border
  src/screens/Departures/components/QuaySection.tsx
Labels: bug

#2028 feat: translations nfk
  ios/Podfile.lock
  package.json
  src/screens/Ticketing/Ticket/TicketInfo.tsx
  src/screens/Ticketing/Tickets/TravelCardInformation.tsx
  src/theme/colors.ts
  src/translations/components/ScreenHeader.ts
  src/translations/dictionary.ts
  src/translations/screens/Onboarding.ts
  src/translations/screens/Profile.ts
  src/translations/screens/Ticket.ts
  src/translations/screens/Tickets.ts
  src/translations/screens/subscreens/ContactSheet.ts
  src/translations/screens/subscreens/DepartureDetails.ts
  src/translations/screens/subscreens/Information.ts
  src/translations/screens/subscreens/Login.ts
  src/translations/screens/subscreens/PurchaseOverview.ts
  src/translations/screens/subscreens/TripDetails.ts
  src/translations/utils.ts
  types/app-orgs.ts
  types/react-native-dotenv.d.ts
  yarn.lock
Labels: OOS

#2171 chore: updates design-system for nfk illustrations
  package.json
  yarn.lock
Labels: OOS

#2087 feat: generic feedback component
  src/components/feedback/FeedbackContext.tsx
  src/components/feedback/GoodOrBadButton.tsx
  src/components/feedback/RenderQuestions.tsx
  src/components/feedback/index.tsx
  src/index.tsx
  src/screens/Departures/StopPlaceView.tsx
  src/screens/TripDetails_v2/components/Trip.tsx
  src/translations/index.ts
  src/translations/screens/Feedback.ts
Labels: Feature
