Repository AtB-AS/mittatb-app, pull requests merged in 2023-12, with the labels that each got.

#4091 feat: Update new iOS Devices
  env/atb/ios-devices.txt
Labels: App

#4092 feat: add analytics for stop place travelFrom and travelTo button
  src/place-screen/components/StopPlaceView.tsx
Labels: :people_holding_hands: Teaminitiativ

#4115 refactor: Remove remaining departures v1 stuff
  src/api/departures/departure-group.ts
  src/api/departures/index.ts
  src/api/departures/types.ts
  src/departure-list/DeparturesList.tsx
  src/departure-list/section-items/line.tsx
  src/departure-list/section-items/more.tsx
  src/departure-list/section-items/quay-section.tsx
  src/departure-list/utils.ts
  src/nearby-stop-places/use-nearest-stops-data.ts
  src/place-screen/hooks/use-departures-data.ts
  src/quay-departures-screen/QuayDeparturesScreenComponent.tsx
  src/quay-departures-screen/index.tsx
  src/quay-departures-screen/types.ts
  src/quay-departures-screen/use-departure-data.ts
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_QuayDeparturesScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/DeparturesWidget.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/use-favorite-departure-data.ts
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/TabNav_DashboardStack.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/navigation-types.ts
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_MapStack/Map_QuayDeparturesScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_MapStack/TabNav_MapStack.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_MapStack/navigation-types.ts
Labels: :wrench: Maintenance, App

#4118 feat: Announcements v2
  src/announcements/AnnouncementsContext.tsx
Labels: App, :iphone: 1.45

#4145 chore: update app name for staging and debug builds
  env/atb/dev/.env
  env/atb/staging/.env
Labels: :wrench: Maintenance, App
