Repository AtB-AS/mittatb-app, pull requests merged in 2023-10, with the labels that each got.

#3908 patch: Async storate dependency patch for the Widget (#3906)
  package.json
  patches/@react-native-async-storage+async-storage+1.19.3.patch
  yarn.lock
Labels: App

#3911 fix: Retry auth no longer done on outdated state
  src/loading-screen/LoadingScreenBoundary.tsx
Labels: App, :bug: Bug

#3935 test: fix tsc error
  .github/workflows/test-performance-android.yml
  e2e/test/pageobjects/departure.overview.page.ts
  e2e/test/specs/departure.e2e.ts
  e2e/test/specs/frontpage.e2e.ts
  e2e/test/utils/element.helper.ts
Labels: Test

#3919 refactor: refactor FareContract components
  src/components/sections/items/LinkSectionItem.tsx
  src/fare-contracts/FareContractInfo.tsx
  src/fare-contracts/PreActivatedFareContractInfo.tsx
  src/fare-contracts/ValidityHeader.tsx
  src/fare-contracts/ValidityLine.tsx
  src/fare-contracts/carnet/CarnetDetails.tsx
  src/fare-contracts/components/FareContractDetail.tsx
  src/fare-contracts/components/FareContractHarborStopPlaces.tsx
  src/fare-contracts/components/WarningMessage.tsx
  src/fare-contracts/details/DetailsContent.tsx
  src/fare-contracts/details/OrderDetails.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_FareContractsScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/TabNav_ProfileStack.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/navigation-types.ts
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/RecentFareContracts/RecentFareContractComponent.tsx
  src/ticketing/types.ts
Labels: :wrench: Maintenance

#3938 test: better waiting for trip results
  e2e/test/flashlight/performanceMeasures.e2e.ts
  e2e/test/pageobjects/map.page.ts
  e2e/test/pageobjects/travelsearch.overview.page.ts
  e2e/test/specs/travelsearch.e2e.ts
Labels: Test

#3939 chore: Eslint doc
  .eslintrc.js
  package.json
  yarn.lock
Labels: :wrench: Maintenance, App

#3940 chore: Not allow variable declaration with var
  .eslintrc.js
  src/api/client.ts
  src/fare-contracts/CompactFareContractInfo.tsx
Labels: :wrench: Maintenance, App

#3941 chore: Eslint prefer self closing tags
  .eslintrc.js
  package.json
  src/components/map/components/BackArrow.tsx
  src/components/page-indicator/PageIndicator.tsx
  src/components/walking-distance/WalkingDistance.tsx
  src/fare-contracts/PurchaseReservation.tsx
  src/fare-contracts/carnet/CarnetFooter.tsx
  src/fare-contracts/components/TravelCardInformation.tsx
  src/index.tsx
  src/information-screen/InformationScreenComponent.tsx
  src/journey-date-picker/JourneyDatePickerScreenComponent.tsx
  src/place-screen/components/DateSelection.tsx
  src/place-screen/components/DepartureTimeSheet.tsx
  src/place-screen/components/StopPlaceAndQuaySelection.tsx
  src/stacks-hierarchy/Root_LoginRequiredForFareProductScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx
  src/travel-details-map-screen/components/CompactTravelDetailsMap.tsx
  src/travel-details-map-screen/components/MapRoute.tsx
  src/travel-details-screens/components/TripLegDecoration.tsx
  src/travel-details-screens/components/TripRow.tsx
  yarn.lock
Labels: :wrench: Maintenance, App

#3943 chore: Eslint rule prefer const
  .eslintrc.js
  eslint-rules/avoid-imports.js
  eslint-rules/import-warning.js
  eslint-rules/translations-warning.js
  src/GeolocationContext.tsx
  src/api/departures/index.ts
  src/api/serviceJourney.ts
  src/components/feedback/Feedback.tsx
  src/components/map/utils.ts
  src/components/sections/Section.tsx
  src/configuration/FirestoreConfigurationContext.tsx
  src/departure-list/utils.ts
  src/fare-contracts/use-validity-line-colors.ts
  src/mobile-token/MobileTokenContext.tsx
  src/mobility/components/filter/use-operator-toggle.tsx
  src/preferences/PreferencesContext.tsx
  src/preferences/storage.ts
  src/situations/utils.ts
  src/stacks-hierarchy/RootStack.tsx
  src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/SelectPaymentMethodSheet.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-defaults.ts
  src/stacks-hierarchy/Root_PurchasePaymentWithCreditCardScreen/use-terminal-state.ts
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/use-trips-query.ts
  src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_DurationScreen/utils.ts
  src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_SummaryScreen/TicketAssistant_SummaryScreen.tsx
  src/stacks-hierarchy/Root_TicketAssistantStack/handle-recommended-ticket-response.ts
  src/stacks-hierarchy/saved-payment-utils.ts
  src/stacks-hierarchy/utils.ts
  src/travel-details-screens/components/Trip.tsx
  src/travel-details-screens/utils.ts
  src/utils/__tests__/use-interval.test.ts
  src/utils/date.ts
Labels: :wrench: Maintenance, App

#3896 feat: Add Kettle SDK
  .gitignore
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/no/mittatb/MainApplication.java
  android/build.gradle
  env/atb/dev/.env
  env/atb/manifests/kettle/AndroidManifest.xml
  env/atb/prodstaging/.env
  env/atb/staging/.env
  env/atb/store/.env
  ios/Configs/Debug.xcconfig
  ios/Configs/Release.xcconfig
  ios/Podfile.lock
  ios/atb.xcodeproj/project.pbxproj
  ios/atb/AppDelegate.mm
  ios/atb/Info.plist
  package.json
  scripts/android/run-android.sh
  scripts/export-workflow-parameters.sh
  scripts/generate-native-assets.sh
  scripts/override-environment.sh
  scripts/utils.sh
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx
  types/react-native-dotenv.d.ts
  yarn.lock
Labels: App

#3951 fix: shows warning when logging in with active tickets
  src/stacks-hierarchy/Root_PurchaseAsAnonymousConsequencesScreen.tsx
Labels: App

#3952 feat: adds bottom sheet with isolated barcode on barcode press
  src/fare-contracts/details/Barcode.tsx
  src/translations/screens/FareContract.ts
Labels: :memo: OOS, App

#3955 feat: Log storage value in Bugsnag breadcrumbs
  src/storage/StorageModel.tsx
Labels: :wrench: Maintenance, App

#3965 fix: Not use quay public code as leg public code
  src/travel-details-screens/utils.ts
Labels: App, :bug: Bug

#3966 chore: Update iOS devices
  env/atb/ios-devices.txt
Labels: App

#3974 refactor: Better encapsulation and logging in auth
  src/analytics/AnalyticsContext.tsx
  src/auth/AuthContext.tsx
  src/auth/types.ts
  src/auth/use-check-if-account-creation-finished.ts
  src/auth/use-fetch-customer-data-after-user-changed.ts
  src/auth/use-subscribe-to-auth-user-change.ts
  src/auth/utils.ts
  src/fare-contracts/PurchaseReservation.tsx
  src/mobile-token/MobileTokenContext.tsx
  src/stacks-hierarchy/Root_ParkingViolationsReporting/Root_ParkingViolationsQr.tsx
  src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
  src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/SelectPaymentMethodSheet.tsx
  src/stacks-hierarchy/Root_PurchasePaymentWithCreditCardScreen/use-terminal-state.ts
  src/stacks-hierarchy/Root_PurchasePaymentWithVippsScreen/use-vipps-state.ts
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PaymentOptionsScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/TicketTabNav_PurchaseTabScreen.tsx
  src/stacks-hierarchy/saved-payment-utils.ts
  src/ticketing/TicketingContext.tsx
Labels: :wrench: Maintenance, App

#3979 refactor: Bugsnag instead of PostHog on loading timeout
  src/loading-screen/LoadingScreenBoundary.tsx
  src/loading-screen/__tests__/use-notify-bugsnag-on-timeout-status.test.ts
  src/loading-screen/use-log-event-on-timeout-status.ts
  src/loading-screen/use-notify-bugsnag-on-timeout-status.ts
  src/utils/bugsnag-utils.ts
Labels: :wrench: Maintenance, App
