Repository AtB-AS/mittatb-app, pull requests merged in 2023-04, with the labels that each got.

#3438 refactor: PurchaseTariffZonesSearchByMapScreen
  src/stacks-hierarchy/Root_PurchaseTariffZonesSearchByMapScreen.tsx
  src/tariff-zones-selector/TariffZonesSelectorButtons.tsx
  src/tariff-zones-selector/TariffZonesSelectorMap.tsx
  src/tariff-zones-selector/index.ts
Labels: :wrench: Maintenance, App

#3442 feat: Notify errors when sign in fails
  src/auth/AuthContext.tsx
  src/login/PhoneInput.tsx
Labels: :wrench: Maintenance, App

#3452 fix: highlighting from/to when selecting zone in the map
  src/stacks-hierarchy/Root_PurchaseTariffZonesSearchByMapScreen.tsx
  src/tariff-zones-selector/TariffZonesSelectorButtons.tsx
  src/tariff-zones-selector/TariffZonesSelectorMap.tsx
Labels: :wrench: Maintenance, App, :iphone: 1.35

#3463 test: adding new test ids
  src/components/bottom-sheet/BottomSheetContainer.tsx
  src/components/sections/items/FavoriteDepartureSectionItem.tsx
  src/departure-list/section-items/FavoriteDialogSheet.tsx
  src/favorite-departures/FavoriteDeparturesScreenComponent.tsx
  src/favorites/FavouriteDepartureToggle.tsx
  src/nearby-stop-places/components/StopPlaces.tsx
  src/service-disruptions/ServiceDisruptionSheet.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/CompactFareContracts.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/DeparturesWidget.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/SelectFavouritesBottomSheet.tsx
Labels: App

#3487 fix: Change widget bundle id to match apple requirements
  env/atb/dev/.env
  env/atb/prodstaging/.env
  env/atb/staging/.env
  env/atb/store/.env
Labels: :iphone: 1.35

#3491 fix: Fix hooks order error in ThemeIcon
  src/components/button/Button.tsx
  src/components/map/components/filter/MapFilter.tsx
  src/components/theme-icon/ThemeIcon.tsx
Labels: App, :bug: Bug

#3492 fix: Duplicate key on recent fare contracts
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/RecentFareContracts/RecentFareContracts.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/types.ts
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/use-recent-fare-contracts.ts
Labels: App, :bug: Bug

#3506 refactor: added eslint rule no-restricted-syntax to restrict wildcard imports
  .eslintrc.js
  src/LocaleProvider.tsx
  src/components/icon-box/utils.ts
  src/components/location-icon/LocationIcon.tsx
  src/components/map/Map.tsx
  src/departure-list/utils.ts
  src/fare-contracts/CompactFareContractInfo.tsx
  src/fare-contracts/PreActivatedFareContractInfo.tsx
  src/fare-contracts/UnknownFareContract.tsx
  src/fare-contracts/carnet/CarnetDetailedView.tsx
  src/fare-contracts/carnet/CarnetDetails.tsx
  src/fare-contracts/carnet/CarnetFareContractInfo.tsx
  src/fare-contracts/details/Barcode.tsx
  src/fare-contracts/details/DetailsContent.tsx
  src/fare-contracts/details/UnknownFareContractDetails.tsx
  src/favorite-departures/FavoriteDeparturesScreenComponent.tsx
  src/favorites/use-on-mark-favourite-departures.tsx
  src/login/ConfirmCode.tsx
  src/login/LoginOptionsScreen.tsx
  src/login/PhoneInput.tsx
  src/nearby-stop-places/components/StopPlaceItem.tsx
  src/place-screen/components/EstimatedCallItem.tsx
  src/place-screen/components/QuaySection.tsx
  src/place-screen/hooks/use-departures-data.ts
  src/select-travel-token-screen/SelectTravelTokenScreenComponent.tsx
  src/service-disruptions/ServiceDisruptionSheet.tsx
  src/situations/SituationBottomSheet.tsx
  src/stacks-hierarchy/Root_AddEditFavoritePlaceScreen/Root_AddEditFavoritePlaceScreen.tsx
  src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/FlexTicketDiscountInfo.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ProductSelectionByProducts.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/MultipleTravellersSelection.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/SingleTravellerSelection.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ZonesSelection.tsx
  src/stacks-hierarchy/Root_ReceiptScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/DeparturesWidget.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/TravelSearchFiltersBottomSheet.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/use-trips-query.ts
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DeleteProfileScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_FavoriteListScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_TravelTokenScreen/ChangeTokenAction.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_TravelTokenScreen/FaqSection.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/FareProducts/FareProductIllustration.tsx
  src/stacks-hierarchy/Root_TipsAndInformation/Root_TipsAndInformation.tsx
Labels: :wrench: Maintenance, App
