Repository AtB-AS/mittatb-app, pull requests merged in 2023-11, with the labels that each got.

#4014 Update: Add a new device for Sebastian
  env/atb/ios-devices.txt
Labels: App

#4013 test: e2e-test improvements
  e2e/index_noLogs/index.js
  e2e/test/pageobjects/departure.overview.page.ts
  e2e/test/pageobjects/frontpage.page.ts
  e2e/test/specs/frontpage.e2e.ts
  e2e/test/specs/travelsearch.e2e.ts
  src/components/message-box/MessageBox.tsx
  src/components/touchable-opacity-or-view/PressableOpacityOrView.tsx
  src/global-messages/GlobalMessage.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/Announcement.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/Announcements.tsx
Labels: Test, App

#4022 test: add notification screen in e2e-tests
  e2e/test/pageobjects/onboarding.page.ts
  e2e/test/specs/onboarding.e2e.ts
  src/stacks-hierarchy/Root_NotificationPermissionScreen.tsx
Labels: Test, App

#4024 refactor: Fix outdated id token error
  package.json
  src/auth/AuthContext.tsx
  src/auth/types.ts
  src/auth/use-check-if-account-creation-finished.ts
  src/auth/use-fetch-customer-data-after-user-changed.ts
  src/auth/use-fetch-id-token-with-custom-claims.ts
  src/auth/use-subscribe-to-auth-user-change.ts
  src/auth/utils.ts
  src/loading-screen/__tests__/use-loading-state.test.ts
  src/loading-screen/__tests__/use-notify-bugsnag-on-timeout-status.test.ts
  yarn.lock
Labels: App, :bug: Bug

#4026 fix: widget set url with env
  ios/departureWidget/APIService.swift
  ios/departureWidget/Info.plist
Labels: App

#4061 feat: Update delete user text
  src/translations/screens/subscreens/DeleteProfile.ts
Labels: :people_holding_hands: Teaminitiativ, App

#4062 feat: Update location onboarding title
  src/translations/screens/LocationWhenInUsePermission.ts
Labels: App

#4071 fix: Updated library and services
  android/app/build.gradle
  android/app/src/beacons/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  ios/Podfile.lock
  package.json
  src/beacons/use-beacons.ts
  src/utils/use-beacons.ts
  yarn.lock
Labels: App
