Repository AtB-AS/mittatb-app, pull requests merged in 2023-09, with the labels that each got.

#3832 chore: fix jest test preset to work with react native
  .github/workflows/tsc.yml
  __tests__/test-setup.js
  __tests__/utils.test.ts
  jest.config.js
Labels: :wrench: Maintenance

#3776 feat: Update new devices job
  .github/workflows/update-devices.yml
  env/atb/dev/.env
  env/atb/ios-devices.txt
  env/atb/prodstaging/.env
  env/atb/staging/.env
  fastlane/Fastfile
Labels: App

#3844 fix: Onboarding triggered multiple times
  src/stacks-hierarchy/Root_OnboardingStack/use-finish-onboarding.ts
Labels: App, :bug: Bug

#3895 feat: Update for new iOS Devices
  env/atb/ios-devices.txt
Labels: App
