Repository AtB-AS/mittatb-app, pull requests merged in 2023-01, with the labels that each got.

#3187 refactor: Remove expand option in ActionSectionItem
  src/components/sections/items/ActionSectionItem.tsx
  src/components/sections/items/ExpandableSectionItem.tsx
  src/departure-list/DeparturesList.tsx
  src/translations/components/Section.ts
Labels: :wrench: Maintenance, App

#3200 build: Use correct secrets for ios store build
  .github/workflows/build-store-ios.yml
Labels: :wrench: Maintenance, App

#3206 refactor: Fix Vipps login button issues
  src/components/vipps-login-button/VippsLoginButton.tsx
  src/login/LoginOptionsScreen.tsx
Labels: App, :bug: Bug

#3236 fix: Small bugs in widget
  ios/departureWidget/Assets.xcassets/Transportation/Metro.imageset/Contents.json
  ios/departureWidget/Assets.xcassets/Transportation/Metro.imageset/Subway.svg
  ios/departureWidget/Structs.swift
  ios/departureWidget/Views/WidgetInfoView.swift
  src/stacks-hierarchy/RootStack.tsx
Labels: App

#3244 refactor: Add an action to refresh certificates
  .github/workflows/ios-certificates.yml
  fastlane/Fastfile
Labels: :wrench: Maintenance, App

#3248 build: Fix Android dependency error
  android/app/build.gradle
Labels: :wrench: Maintenance, App
