Repository AtB-AS/mittatb-app, pull requests merged in 2024-08, with the labels that each got.

#4648 feat: Consolidate radio button group
  src/components/sections/RadioGroupSection.tsx
  src/components/sections/index.ts
  src/components/sections/items/RadioSectionItem.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx
  src/storybook/stories/Section.stories.tsx
Labels: :people_holding_hands: Teaminitiativ, App

#4657 fix: issue with non-transit legs trying to show ticket info
  src/travel-details-screens/TripDetailsScreenComponent.tsx
Labels: :bug: Bug, :iphone: 1.54

#4662 test: check more results when filtering travel searches
  e2e/test/pageobjects/travelsearch.overview.page.ts
  e2e/test/specs/travelsearch.filter.e2e.ts
Labels: Test

#4672 build: Split update devices job to be run in serial
  .github/actions/update-devices/action.yml
  .github/workflows/update-devices.yml
Labels: App, :bug: Bug

#4685 test: accept time difference
  e2e/test/specs/travelsearch.e2e.ts
  e2e/test/utils/time.helper.ts
Labels: Test

#4686 chore: move vipps login button to top
  src/stacks-hierarchy/Root_LoginOptionsScreen.tsx
Labels: App

#4693 fix: add boat-carnet ticket illustration type
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/TicketingTileIllustration.tsx
Labels: App, :bug: Bug
