Repository AtB-AS/mittatb-app, pull requests merged in 2024-12, with the labels that each got.

#4859 feat: add submode rule variable on trip and departure details
  src/travel-details-screens/DepartureDetailsScreenComponent.tsx
  src/travel-details-screens/components/Trip.tsx
Labels: App

#4857 refactor: fix some departure favorite exhaustive deps warnings
  src/place-screen/components/QuaySection.tsx
  src/place-screen/components/QuayView.tsx
  src/place-screen/components/StopPlacesView.tsx
  src/translations/screens/Departures.ts
Labels: :wrench: Maintenance, App

#4851 feat: Use PurchaseSelectionType in Traveller components
  src/purchase-selection/__tests__/purchase-selection-builder-user-profiles.test.ts
  src/purchase-selection/purchase-selection-builder.ts
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelection.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelectionSheet.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/MultipleTravellersSelection.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/SingleTravellerSelection.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/types.ts
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/use-user-count-state.ts
Labels: :wrench: Maintenance, App

#4873 test: e2e test change for departure details header
  e2e/test/pageobjects/departure.details.page.ts
  e2e/test/specs/departure.e2e.ts
  src/travel-details-screens/DepartureDetailsScreenComponent.tsx
Labels: Test

#4872 chore: Add eslint rules for not leaking values to jsx
  .eslintrc.js
  package.json
  src/components/screen-view/FullScreenView.tsx
  src/mobility/components/MobilityStat.tsx
  src/stacks-hierarchy/Root_ParkingViolationsReporting/components/ScreenContainer.tsx
  src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/PreassignedFareProductSummary.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_EditProfileScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx
  src/travel-details-screens/components/TripSection.tsx
  yarn.lock
Labels: :wrench: Maintenance, App

#4877 fix: Only stop places checkbox label color
  src/components/checkbox/CheckboxWithLabel.tsx
  src/stacks-hierarchy/Root_LocationSearchByTextScreen/components/LocationSearchContent.tsx
Labels: App, :bug: Bug

#4879 chore: Add strandlie to codeowners
  .github/CODEOWNERS
Labels: :wrench: Maintenance, App

#4878 feat: Store only stop places checkbox state on device
  src/stacks-hierarchy/Root_LocationSearchByTextScreen/components/LocationSearchContent.tsx
  src/storage/StorageModel.tsx
  src/utils/__tests__/use-persisted-bool-state.test.ts
  src/utils/use-persisted-bool-state.ts
Labels: :wrench: Maintenance, App

#4889 test: add test-ids
  src/place-screen/components/DepartureTimeSheet.tsx
  src/place-screen/components/QuayView.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/FareProductHeader.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/FlexTicketDiscountInfo.tsx
  src/travel-aid/TravelAidScreenComponent.tsx
  src/travel-details-screens/DepartureDetailsScreenComponent.tsx
Labels: Test

#4892 test: more visual tests
  .github/workflows/test-e2e-android.yml
  .github/workflows/test-performance-android.yml
  .github/workflows/test-visual-android.yml
  e2e/screenshots/.gitignore
  e2e/screenshots/visualTests/baseline/departures-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/departures_departureDetails-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/departures_departureDetailsContent-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/departures_departuresItem0-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/departures_journeyAid-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/departures_journeyAidSection-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/frontpage-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/profile_defaultTraveller-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/profile_notifications-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/singleTicketElem-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_flexDiscountExpanded-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_nightTicket-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_nightTicket2-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_purchaseSummary-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_purchaseSummaryMC-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_selectTraveller-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_singleTicket-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_singleTicketElem-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_ticketInformationNight-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_ticketInformationSingle-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/travelSearch_details-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/travelSearch_results-android-1080x2340.png
  e2e/test/conf/config.ts
  e2e/test/pageobjects/accessibility.page.ts
  e2e/test/pageobjects/departure.details.page.ts
  e2e/test/pageobjects/departure.search.page.ts
  e2e/test/pageobjects/journey.aid.page.ts
  e2e/test/pageobjects/onboarding.page.ts
  e2e/test/pageobjects/purchase.overview.page.ts
  e2e/test/pageobjects/time.picker.page.ts
  e2e/test/pageobjects/travelsearch.filter.page.ts
  e2e/test/pageobjects/travelsearch.overview.page.ts
  e2e/test/specs/travelsearch.e2e.ts
  e2e/test/utils/app.helper.ts
  e2e/test/utils/element.helper.ts
  e2e/test/utils/visual.helper.ts
  e2e/test/visualTests/specs/visual.departures.e2e.ts
  e2e/test/visualTests/specs/visual.other.e2e.ts
  e2e/test/visualTests/specs/visual.ticket.e2e.ts
  e2e/test/visualTests/specs/visual.travelsearch.e2e.ts
  e2e/test/visualTests/specs/visualTests.e2e.ts
Labels: Test

#4894 refactor: Use generated bff types with inline fragments
  src/api/types/generated/DeparturesQuery.ts
  src/api/types/generated/NearestStopPlacesQuery.ts
  src/api/types/generated/StopsDetailsQuery.ts
  src/api/types/generated/fragments/estimated-calls.ts
  src/api/types/generated/fragments/journey-patterns.ts
  src/api/types/generated/fragments/quays.ts
  src/api/types/generated/fragments/service-journeys.ts
  src/api/types/generated/fragments/situations.ts
  src/api/types/generated/fragments/trips.ts
Labels: :wrench: Maintenance, App

#4898 fix: disable fetching of vehicles when out of focus
  src/travel-details-screens/use-get-service-journey-vehicles.ts
Labels: App, :bug: Bug, :iphone: 1.61
