Repository AtB-AS/mittatb-app, pull requests merged in 2024-03, with the labels that each got.

#4363 refactor: rename function isViewVisibleOnScreen to isElementFullyInsideScreen
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_ActiveFareProductsTabScreen.tsx
  src/utils/__tests__/is-element-fully-inside-screen.test.ts
  src/utils/__tests__/is-view-visible-on-screen.test.ts
  src/utils/is-element-fully-inside-screen.ts
  src/utils/is-view-visible-on-screen.ts
Labels: :wrench: Maintenance, App

#4364 refactor: rework TravellerSelection to add non-clickable section
  src/components/sections/items/GenericClickableSectionItem.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelection.tsx
Labels: :wrench: Maintenance, App

#4389 fix: Only show login onboarding if not logged in
  src/onboarding/onboarding-config.ts
Labels: App, :bug: Bug

#4395 test: e2e-ticketing tests
  e2e/test/pageobjects/onboarding.page.ts
  e2e/test/pageobjects/purchase.overview.page.ts
  e2e/test/pageobjects/purchase.payment.page.ts
  e2e/test/pageobjects/purchase.summary.page.ts
  e2e/test/pageobjects/ticket.page.ts
  e2e/test/pageobjects/travelsearch.overview.page.ts
  e2e/test/specs/ticket.e2e.ts
  src/anonymous-purchase-consequences-screen/AnonymousPurchaseConsequencesScreenComponent.tsx
  src/components/checkbox/Checkbox.tsx
  src/components/message-info-box/MessageInfoBox.tsx
  src/onboarding/OnboardingFullScreenView.tsx
  src/stacks-hierarchy/Root_LoginRequiredForFareProductScreen.tsx
  src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
  src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/SelectPaymentMethodSheet.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelection.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelectionSheet.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/MultipleTravellersSelection.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ZonesSelection.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/AnonymousPurchaseWarning.tsx
Labels: Test

#4407 fix: check for user being undefined on auth state change
  src/onboarding/OnboardingContext.tsx
Labels: App, :bug: Bug

#4399 fix: fixed scroll of ActiveTokenOnPhoneRequiredForFareProductScreen
  src/stacks-hierarchy/Root_ActiveTokenOnPhoneRequiredForFareProductScreen.tsx
Labels: App, :bug: Bug

#4400 fix: Presented sent date should show the created date
  src/fare-contracts/FareContractView.tsx
  src/fare-contracts/ValidityHeader.tsx
  src/fare-contracts/details/DetailsContent.tsx
Labels: App, :bug: Bug
