Repository AtB-AS/mittatb-app, pull requests merged in 2024-11, with the labels that each got.

#4790 test: add test-ids for the map
  src/components/map/Map.tsx
  src/components/map/components/filter/MapFilter.tsx
  src/components/map/components/filter/MapFilterSheet.tsx
  src/mobility/components/filter/FormFactorFilter.tsx
Labels: Test, App

#4788 test: visual tests of the app
  .github/workflows/test-visual-android.yml
  e2e/conf/android.conf.local.appcenter.ts
  e2e/conf/android.conf.local.dev.ts
  e2e/conf/android.conf.ts
  e2e/package.json
  e2e/screenshots/.gitignore
  e2e/screenshots/visualTests/baseline/frontpage-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/singleTicketElem-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets-android-1080x2340.png
  e2e/scripts/remove-navigation-bar.sh
  e2e/test/utils/visual.helper.ts
  e2e/test/visualTests/specs/visualTests.e2e.ts
  e2e/tsconfig.json
  e2e/yarn.lock
Labels: Test, App

#4786 feat: Add nynorsk feature toggle
  src/feature-toggles/toggle-specifications.ts
  src/remote-config.ts
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_LanguageScreen.tsx
Labels: :wrench: Maintenance, App

#4791 test: run perf tests per feature
  .github/actions/python-setup/action.yml
  .github/workflows/test-e2e-android.yml
  .github/workflows/test-performance-android.yml
  e2e/performance/createPerformanceSummary.ts
  e2e/performance/removeMeasures.py
  e2e/scripts/handle-flashlight-results.sh
  e2e/scripts/run-flashlight-tests.sh
  e2e/test/flashlight/performanceMeasures_map.e2e.ts
  e2e/test/flashlight/performanceMeasures_travelsearch.e2e.ts
  e2e/test/pageobjects/map.page.ts
  e2e/test/specs/travelsearch.filter.e2e.ts
Labels: Test

#4809 feat: Make buttons in loading state not pressable
  src/components/button/Button.tsx
Labels: :wrench: Maintenance, App

#4810 feat: various travel aid tweaks
  src/translations/screens/subscreens/TravelAid.ts
  src/travel-aid/TravelAidScreenComponent.tsx
  src/travel-aid/use-travel-aid-data.tsx
  src/travel-details-screens/DepartureDetailsScreenComponent.tsx
Labels: Blue button - phase 1

#4813 test: emulator upgrade
  .github/workflows/test-e2e-android.yml
  .github/workflows/test-performance-android.yml
  .github/workflows/test-visual-android.yml
  e2e/test/pageobjects/travelsearch.overview.page.ts
  e2e/test/specs/travelsearch.e2e.ts
Labels: Test

#4841 feat: Not available ticket text improvement
  src/translations/screens/subscreens/PurchaseOverview.ts
Labels: :wrench: Maintenance, App

#4842 fix: Only enable get active booking when feature flag true
  src/mobility/queries/use-active-shmo-booking-query.tsx
Labels: App

#4840 feat: Not always announce scheduled time in travel aid
  src/travel-aid/TravelAidScreenComponent.tsx
Labels: :wrench: Maintenance, App

#4847 fix: Purchase builder products input from API
  src/purchase-selection/use-purchase-selection-builder.ts
  src/ticketing/use-get-fare-products-query.tsx
Labels: App, :bug: Bug
