Repository AtB-AS/mittatb-app, pull requests merged in 2024-02, with the labels that each got.

#4277 test: make the e2e tests run
  .github/workflows/test-e2e-android.yml
  .github/workflows/test-performance-android.yml
  e2e/conf/android.conf.local.appcenter.ts
  e2e/conf/android.conf.local.dev.ts
  e2e/conf/android.conf.ts
  e2e/conf/wdio.conf.ts
  e2e/package.json
  e2e/scripts/install-flashlight.sh
  e2e/test/flashlight/performanceMeasures.e2e.ts
  e2e/test/pageobjects/departure.details.page.ts
  e2e/test/pageobjects/departure.overview.page.ts
  e2e/test/pageobjects/departure.search.page.ts
  e2e/test/pageobjects/favorite.page.ts
  e2e/test/pageobjects/frontpage.page.ts
  e2e/test/pageobjects/onboarding.page.ts
  e2e/test/pageobjects/search.page.ts
  e2e/test/pageobjects/ticket.page.ts
  e2e/test/pageobjects/travelsearch.details.page.ts
  e2e/test/pageobjects/travelsearch.overview.page.ts
  e2e/test/specs/departure.e2e.ts
  e2e/test/specs/frontpage.e2e.ts
  e2e/test/specs/onboarding.e2e.ts
  e2e/test/specs/travelsearch.e2e.ts
  e2e/test/utils/app.helper.ts
  e2e/test/utils/element.helper.ts
  e2e/test/utils/jestAssertions.ts
  e2e/test/utils/navigation.helper.ts
  e2e/test/utils/time.helper.ts
  e2e/tsconfig.json
  e2e/yarn.lock
  package.json
  src/components/button/Button.tsx
  yarn.lock
Labels: Test, App

#4314 feat: add "new" label to notifications in my profile
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx
Labels: App, PI: Push notifications

#4317 fix: hide token warning message if buying ticket for someone else
  src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx
Labels: App

#4327 feat: Add feature flag for server time
  src/index.tsx
  src/remote-config.ts
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx
  src/storage/StorageModel.tsx
  src/time/TimeContext.tsx
  src/time/index.ts
  src/time/use-server-time-enabled.ts
Labels: :wrench: Maintenance, App

#4337 update: A new iOS Device for Hannah
  env/atb/ios-devices.txt
Labels: :wrench: Maintenance

#4347 fix: Correct value for token refresh percentage
  src/mobile-token/mobileTokenClient.ts
Labels: App, :bug: Bug

#4349 fix: fix VAT amount calculation
  src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
Labels: App

#4352 fix: Update the position always on prompt text
  src/translations/screens/ShareTravelHabits.ts
Labels: App, PI: Beacons user onboarding, :iphone: 1.47

#4354 refactor: change LinkSectionItem a11y role to button
  src/chat/ContactSheet.tsx
  src/components/feedback/SubmittedComponent.tsx
  src/components/sections/items/LinkSectionItem.tsx
  src/components/sections/items/MessageSectionItem.tsx
  src/fare-contracts/PurchaseReservation.tsx
  src/fare-contracts/details/DetailsContent.tsx
  src/information-screen/InformationScreenComponent.tsx
  src/loading-screen/LoadingErrorScreen.tsx
  src/mobility/components/OperatorActionButton.tsx
  src/service-disruptions/ServiceDisruptionSheet.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/FlexTicketDiscountInfo.tsx
  src/stacks-hierarchy/Root_PurchasePaymentWithVippsScreen/Root_PurchasePaymentWithVippsScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/Announcement.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PrivacyScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx
  src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_CategoryPickerScreen.tsx
Labels: App, a11y

#4356 test: handle popovers in e2e test
  e2e/package.json
  e2e/test/flashlight/performanceMeasures.e2e.ts
  e2e/test/utils/app.helper.ts
  src/components/popover/PopOver.tsx
Labels: Test
