Repository AtB-AS/mittatb-app, pull requests merged in 2024-01, with the labels that each got.

#4181 chore: Add flipper plugin for async storage
  docs/Debugging.md
  package.json
  src/index.tsx
  src/utils/is-qa-or-dev.ts
  yarn.lock
Labels: :wrench: Maintenance, App

#4186 refactor: Fix gap on payment options screen
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PaymentOptionsScreen.tsx
Labels: :wrench: Maintenance, App

#4189 Feat: Add beacons after being removed from 1.45
  android/app/src/main/AndroidManifest.xml
  env/atb/dev/.env
  env/atb/prodstaging/.env
  env/atb/staging/.env
Labels: App

#4190 fix: refetch notification config on auth user change
  src/notifications/use-config.tsx
Labels: App, :bug: Bug, PI: Push notifications

#4200 fix: Update Beacons context to handle better status updates
  src/beacons/BeaconsContext.tsx
Labels: PI: Beacons user onboarding

#4211 chore: Update podfile.lock
  ios/Podfile.lock
Labels: :wrench: Maintenance, App

#4239 fix: typo in profile page
  src/translations/screens/Profile.ts
Labels: App, :bug: Bug

#4251 Refactor use-ticket-info and remove Root_CarnetDetailsScreen
  src/components/screen-header/use-ticket-info.tsx
  src/fare-contracts/FareContractAndReservationsList.tsx
  src/fare-contracts/FareContractInfo.tsx
  src/fare-contracts/carnet/CarnetFareContractInfo.tsx
  src/stacks-hierarchy/RootStack.tsx
  src/stacks-hierarchy/Root_CarnetDetailsScreen.tsx
  src/stacks-hierarchy/Root_FareContractDetailsScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/Dashboard_RootScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/CompactFareContracts.tsx
  src/stacks-hierarchy/navigation-types.ts
  src/ticketing/utils.ts
Labels: :wrench: Maintenance, App

#4276 test: add test-ids for onboarding
  src/anonymous-purchase-consequences-screen/AnonymousPurchaseConsequencesScreenComponent.tsx
  src/components/bottom-sheet/BottomSheetHeader.tsx
  src/onboarding-screen/OnboardingFullScreenView.tsx
  src/onboarding-screen/OnboardingScreenComponent.tsx
  src/stacks-hierarchy/Root_LoginOptionsScreen.tsx
Labels: Test, App
