Repository AtB-AS/mittatb-app, pull requests merged in 2024-05, with the labels that each got.

#4477 refactor: Add more logging to ticketing Firestore subscriptions
  src/ticketing/TicketingContext.tsx
Labels: :wrench: Maintenance, App, :iphone: 1.50

#4471 test: e2e tests for travel search
  e2e/test/pageobjects/onboarding.page.ts
  e2e/test/pageobjects/travelsearch.details.page.ts
  e2e/test/pageobjects/travelsearch.filter.page.ts
  e2e/test/pageobjects/travelsearch.overview.page.ts
  e2e/test/specs/ticket.e2e.ts
  e2e/test/specs/travelsearch.e2e.ts
  e2e/test/specs/travelsearch.filter.e2e.ts
  e2e/test/utils/app.helper.ts
  e2e/test/utils/time.helper.ts
  e2e/test/utils/utils.ts
  src/components/icon-box/TransportationIconBox.tsx
  src/journey-date-picker/JourneyDatePickerScreenComponent.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/SingleTravellerSelection.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/NonTransitResults.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/SelectedFiltersButtons.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/TravelSearchFiltersBottomSheet.tsx
Labels: Test, App

#4479 feat: add auth retry when there is no customer number
  src/stacks-hierarchy/Root_TabNavigatorStack/Root_TabNavigatorStack.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx
  src/translations/screens/Profile.ts
Labels: App

#4476 refactor: Clear queries on user change
  src/auth/AuthContext.tsx
  src/auth/use-clear-queries-on-user-change.ts
  src/index.tsx
  src/mobile-token/hooks/useListRemoteTokensQuery.tsx
  src/mobility/queries/use-fare-product-benefits-query.tsx
  src/mobility/queries/use-user-benefits-query.tsx
  src/mobility/queries/use-value-code-query.tsx
  src/notifications/use-notification-config.tsx
  src/queries/get-profile-query.ts
  src/stacks-hierarchy/RootStack.tsx
  src/ticketing/use-get-fare-products-query.tsx
Labels: :wrench: Maintenance, App

#4492 test: test-id for rental bikes in travel search
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/NonTransitResults.tsx
Labels: Test

#4497 fix: Apple privacy manifest error MapBox
  ios/Podfile
  ios/Podfile.lock
Labels: App, :bug: Bug

#4495 fix: Loading boundary based on derived state
  src/loading-screen/__tests__/use-loading-state.test.ts
  src/loading-screen/use-loading-state.ts
Labels: :wrench: Maintenance, App

#4510 chore: fix `notifyBugsnag` function by making `errorGroupHash` optional
  src/auth/use-fetch-id-token-with-custom-claims.ts
  src/loading-screen/__tests__/use-notify-bugsnag-on-timeout-status.test.ts
  src/loading-screen/use-notify-bugsnag-on-timeout-status.ts
  src/mobile-token/MobileTokenContext.tsx
  src/mobile-token/hooks/useGetSignedTokenQuery.tsx
  src/stacks-hierarchy/Root_PurchasePaymentScreen/WebViewTerminal.tsx
  src/ticketing/TicketingContext.tsx
  src/utils/bugsnag-utils.ts
Labels: :wrench: Maintenance, App

#4507 feat: remove new label from on-behalf-of feature
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelection.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/MultipleTravellersSelection.tsx
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/SingleTravellerSelection.tsx
Labels: :people_holding_hands: Teaminitiativ, App, :iphone: 1.51

#4506 fix: Clear queries before id token fetch
  src/auth/AuthContext.tsx
  src/auth/use-fetch-id-token-with-custom-claims.ts
Labels: App, :bug: Bug, :iphone: 1.51

#4533 test: accept travel time variations
  e2e/test/specs/travelsearch.e2e.ts
  e2e/test/utils/time.helper.ts
Labels: Test, App

#4536 feat: remove check for several carnets to show consume button
  src/ticketing/utils.ts
Labels: PI: Klippekort i app, App

#4540 feat: add ThemeIcon to storybook
  .storybook/storybook.requires.js
  src/storybook/stories/ThemeIcon.stories.tsx
Labels: :wrench: Maintenance, App

#4542 fix: use correct icon size in FareContractStatusSymbol
  src/fare-contracts/components/FareContractStatusSymbol.tsx
Labels: :wrench: Maintenance, App

#4550 refactor: sort storage model keys enum alphabetically
  src/storage/StorageModel.tsx
Labels: :wrench: Maintenance, App
