Repository AtB-AS/mittatb-app, pull requests merged in 2024-06, with the labels that each got.

#4588 refactor: Bugsnag breadcrumb when invalidating tokens list
  src/mobile-token/MobileTokenContext.tsx
Labels: :wrench: Maintenance, App

#4584 fix: Not resubscribe auth on enable_intercom change
  src/auth/AuthContext.tsx
  src/auth/use-subscribe-to-auth-user-change.ts
  src/auth/use-update-intercom-on-user-change.ts
Labels: App, :bug: Bug

#4602 fix: filter out successful reservations for sent to other tickets.
  src/ticketing/TicketingContext.tsx
Labels: App, :bug: Bug, :iphone: 1.53

#4609 feat: hide payment method and price on refunded tickets
  src/fare-contracts/details/OrderDetails.tsx
Labels: App
