Repository AtB-AS/mittatb-app, pull requests merged in 2025-03, with the labels that each got.

#5051 refactor: remove use of useThemeColorForTransportMode
  src/components/icon-box/TransportationIconBox.tsx
  src/modules/fare-contracts/components/InspectionSymbol.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/FareProducts/FareProductTile.tsx
  src/utils/use-transport-color.ts
Labels: :wrench: Maintenance, App

#5061 fix: Missing requires booking text on trip result
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx
Labels: App, :bug: Bug

#5088 fix: use correct text color for button loading indicator
  src/components/button/Button.tsx
Labels: App, :bug: Bug

#5085 fix: make spacing even on spacious sections
  src/components/sections/items/CounterSectionItem.tsx
  src/components/sections/use-section-item.ts
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/MultipleTravellersSelection.tsx
Labels: App, :bug: Bug

#5086 refactor: update token toggle styling
  src/components/message-info-text/MessageInfoText.tsx
  src/select-travel-token-screen/SelectTravelTokenScreenComponent.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_TravelTokenScreen/Profile_TravelTokenScreen.tsx
  src/token-toggle-info/TokenToggleInfo.tsx
Labels: :wrench: Maintenance, App

#5103 feat: add token renewal logic based on token and device details
  src/mobile-token/MobileTokenContext.tsx
  src/mobile-token/hooks/use-validate-token.tsx
  src/mobile-token/index.ts
  src/mobile-token/types.ts
Labels: :wrench: Maintenance, App, Mobile Token :skunk:

#5104 fix: add missing query dependency to token toggle mutation
  src/mobile-token/hooks/use-toggle-token-mutation.tsx
Labels: :wrench: Maintenance, App, Mobile Token :skunk:

#5107 fix: use fare contract id as key in active tickets list
  src/modules/fare-contracts/FareContractAndReservationsList.tsx
Labels: App, :bug: Bug
