Repository AtB-AS/mittatb-app, pull requests merged in 2025-05, with the labels that each got.

#5148 feat: add Mapbox env variables for FRAM, NFK and Troms
  env/fram/dev/.env
  env/fram/staging/.env
  env/fram/store/.env
  env/nfk/dev/.env
  env/nfk/prodstaging/.env
  env/nfk/staging/.env
  env/nfk/store/.env
  env/troms/dev/.env
  env/troms/staging/.env
  env/troms/store/.env
Labels: App, :memo: OMS

#5151 feat: add debug menu for simulating remote token inspectability
  src/mobile-token/MobileTokenContext.tsx
  src/mobile-token/hooks/use-list-remote-tokens-query.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx
Labels: App, Mobile Token :skunk:

#5158 feat: add error message for school ticket consumption
  src/api/utils.ts
  src/modules/fare-contracts/components/ConsumeCarnetBottomSheet.tsx
  src/translations/screens/FareContract.ts
Labels: App

#5167 fix: don't read zones if there are no zones on recent ticket results.
  src/recent-fare-contracts/use-recent-fare-contracts.ts
Labels: :wrench: Maintenance, App

#5182 fix: support tinted variant of widget
  ios/departureWidget/Views/ChipView.swift
  ios/departureWidget/Views/DepartureTimesView.swift
  ios/departureWidget/Views/WidgetInfoView.swift
Labels: App, :bug: Bug

#5183 fix: prevent crash on Android when selecting favorite departure
  src/modules/native-bridges/widget-updater.ts
Labels: App, :bug: Bug, :iphone: 1.67

#5159 refactor: Moved DateSelection from place-screen to date-picker
  src/components/date-selection/DatePickerSheet.tsx
  src/components/date-selection/DateSelection.tsx
  src/components/date-selection/index.ts
  src/components/date-selection/types.ts
  src/date-picker/index.ts
  src/date-picker/types.ts
  src/modules/map/components/DeparturesDialogSheet.tsx
  src/screen-components/place-screen/PlaceScreenComponent.tsx
  src/screen-components/place-screen/components/QuayView.tsx
  src/screen-components/place-screen/components/StopPlacesView.tsx
  src/screen-components/place-screen/index.tsx
  src/screen-components/place-screen/types.ts
  src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/StartTimeSelection.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/use-favorite-departure-data.ts
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/use-non-transit-trips-query.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/utils.ts
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/types.ts
Labels: App

#5191 fix: use correct state for fare contract pull-to-refresh spinner
  src/modules/ticketing/TicketingContext.tsx
  src/modules/ticketing/use-fare-contracts.ts
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_AvailableFareContractsTabScreen.tsx
Labels: App, :bug: Bug

#5192 feat: sort ticket history page by creation
  src/modules/fare-contracts/FareContractAndReservationsList.tsx
  src/modules/fare-contracts/__tests__/sort-fc-or-reservation.test.ts
  src/modules/fare-contracts/index.ts
  src/modules/fare-contracts/sort-fc-or-reservation.ts
  src/screen-components/ticket-history/TicketHistoryScreenComponent.tsx
Labels: quickwin, App

#5206 fix: hide `Show Trip` button if no polyline is received
  src/screen-components/travel-details-screens/DepartureDetailsScreenComponent.tsx
Labels: bugsnag, App, :bug: Bug

#5207 test: update e2e tests
  e2e/package.json
  e2e/screenshots/visualTests/baseline/departures_departureDetailsContent-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/departures_journeyAid-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/departures_journeyAidSection-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/departures_quay0-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/frontpage-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/profile_defaultTraveller-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/profile_notifications-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_flexDiscountExpanded-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_nightTicket-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_nightTicket2-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_purchaseSummary-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_purchaseSummaryMC-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_selectTraveller-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_singleTicket-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_singleTicketElem-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_ticketInformationNight-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_ticketInformationSingle-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/travelSearch_filter_bottom-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/travelSearch_filter_top-android-1080x2340.png
  e2e/scripts/run-flashlight-tests.sh
  e2e/test/conf/config.ts
  e2e/test/pageobjects/purchase.payment.page.ts
  e2e/test/specs/myProfile.e2e.ts
  e2e/test/specs/ticket.e2e.ts
  e2e/test/specs/travelsearch.e2e.ts
  e2e/test/specs/travelsearch.filter.e2e.ts
  e2e/test/utils/alert.helper.ts
  e2e/test/visualTests/specs/visual.departures.e2e.ts
  e2e/test/visualTests/specs/visual.other.e2e.ts
  e2e/test/visualTests/specs/visual.ticket.e2e.ts
  src/modules/payment/MultiplePaymentMethodsRadioSection.tsx
Labels: Test
