Repository AtB-AS/mittatb-app, pull requests merged in 2025-02, with the labels that each got.

#4993 fix: Align small tertiary button typography with Figma
  src/components/button/Button.tsx
Labels: :wrench: Maintenance, App

#5001 fix: force build as strings
  .github/workflows/build-staging-android.yml
Labels: App

#5002 fix: force true also on push for android
  .github/workflows/build-staging-android.yml
Labels: App

#4999 refactor: Decouple navigation object on fare contract lists
  src/fare-contracts/FareContractAndReservationsList.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_TicketHistoryScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketHistoryScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_AvailableFareContractsTabScreen.tsx
  src/ticket-history/TicketHistoryScreenComponent.tsx
Labels: :wrench: Maintenance, App

#5005 feat: swap favorite and map button on departure details
  src/travel-details-screens/DepartureDetailsScreenComponent.tsx
Labels: quickwin, App

#5004 fix: prevent markdown overflow in global messages
  src/components/text/ThemeText.tsx
  src/stacks-hierarchy/Root_TicketInformationScreen.tsx
Labels: App, :bug: Bug

#5003 feat: Only stop places checked as default
  src/stacks-hierarchy/Root_AddEditFavoritePlaceScreen/Root_AddEditFavoritePlaceScreen.tsx
  src/stacks-hierarchy/Root_LocationSearchByTextScreen/Root_LocationSearchByTextScreen.tsx
  src/stacks-hierarchy/Root_LocationSearchByTextScreen/components/LocationSearchContent.tsx
  src/stacks-hierarchy/Root_LocationSearchByTextScreen/navigation-types.ts
  src/stacks-hierarchy/Root_SearchStopPlaceScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_NearbyStopPlacesScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/Dashboard_RootScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DeparturesStack/Departures_NearbyStopPlacesScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_NearbyStopPlacesScreen.tsx
  src/utils/__tests__/use-persisted-bool-state.test.ts
  src/utils/use-persisted-bool-state.ts
Labels: :people_holding_hands: Team initiative, App, :iphone: 1.63

#5008 fix: remove redundant section around filter RadioSegments
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/TravelSearchPreference.tsx
Labels: :wrench: Maintenance, App

#5014 fix: Show product name on recent fare contract
  src/recent-fare-contracts/RecentFareContract.tsx
Labels: App, :bug: Bug

#5017 fix: use frontText instead of lineName in departures widget
  ios/AtbAppIntent/IntentHandler.swift
  ios/departureWidget/Provider.swift
  ios/departureWidget/Structs.swift
  ios/departureWidget/WidgetViewModel.swift
Labels: App, :bug: Bug, :iphone: 1.63

#5019 refactor: Remove transitionPreset not serialisable warning
  src/stacks-hierarchy/Root_LocationSearchByTextScreen/hooks.ts
  src/stacks-hierarchy/Root_LoginAvailableFareContractWarningScreen.tsx
  src/stacks-hierarchy/Root_LoginOptionsScreen.tsx
  src/stacks-hierarchy/Root_LoginPhoneInputScreen.tsx
  src/stacks-hierarchy/Root_LoginRequiredForFareProductScreen.tsx
  src/stacks-hierarchy/Root_PurchaseAsAnonymousConsequencesScreen.tsx
  src/stacks-hierarchy/Root_ScooterHelp/Root_ContactScooterOperatorScreen.tsx
  src/stacks-hierarchy/Root_ScooterHelp/Root_ScooterHelpScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_NearbyStopPlacesScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DeparturesStack/Departures_NearbyStopPlacesScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_NearbyStopPlacesScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/TicketTabNav_PurchaseTabScreen.tsx
  src/stacks-hierarchy/navigation-types.ts
  src/stacks-hierarchy/navigation-utils.ts
Labels: :wrench: Maintenance, App

#5021 refactor: Make backgroundColor mandatory on secondary/tertiary buttons
  src/components/button/Button.tsx
  src/components/map/components/DeparturesDialogSheet.tsx
  src/components/snackbar/Snackbar.tsx
  src/mobility/components/ScooterSheet.tsx
  src/modules/fare-contracts/PurchaseReservation.tsx
  src/place-screen/PlaceScreenComponent.tsx
  src/place-screen/components/DateSelection.tsx
  src/place-screen/components/QuayView.tsx
  src/place-screen/components/StopPlacesView.tsx
  src/service-disruptions/ServiceDisruptionSheet.tsx
  src/stacks-hierarchy/Root_ScooterHelp/bottom-sheets/ImageConfirmationBottomSheet.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/SelectFavouritesBottomSheet.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx
  src/travel-details-screens/DepartureDetailsScreenComponent.tsx
  src/travel-details-screens/components/PaginatedDetailsHeader.tsx
Labels: :wrench: Maintenance, App

#5030 test: update the visual tests without time picker
  e2e/screenshots/visualTests/baseline/departures-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/departures_departureDetails-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/departures_departureDetailsContent-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/departures_departuresItem0-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/departures_journeyAid-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/departures_journeyAidSection-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/departures_quay0-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/frontpage-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/profile_defaultTraveller-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/profile_notifications-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_flexDiscountExpanded-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_nightTicket-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_nightTicket2-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_purchaseSummary-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_purchaseSummaryMC-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_selectTraveller-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_singleTicket-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_singleTicketElem-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_ticketInformationNight-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/tickets_ticketInformationSingle-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/travelSearch_details-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/travelSearch_filter_bottom-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/travelSearch_filter_top-android-1080x2340.png
  e2e/screenshots/visualTests/baseline/travelSearch_results-android-1080x2340.png
  e2e/test/pageobjects/departure.search.page.ts
  e2e/test/pageobjects/purchase.overview.page.ts
  e2e/test/pageobjects/travelsearch.filter.page.ts
  e2e/test/specs/travelsearch.e2e.ts
  e2e/test/utils/time.helper.ts
  e2e/test/visualTests/specs/visual.departures.e2e.ts
  e2e/test/visualTests/specs/visual.ticket.e2e.ts
  e2e/test/visualTests/specs/visual.travelsearch.e2e.ts
  src/travel-details-screens/DepartureDetailsScreenComponent.tsx
Labels: Test

#5029 feat: upgrade mobile token SDK to version 3.3.2
  ios/Podfile
  ios/Podfile.lock
  package.json
  patches/@entur-private+abt-token-state-react-native-lib+2.1.6.patch
  src/chat/use-intercom-metadata.ts
  src/mobile-token/DebugSabotage.tsx
  src/mobile-token/MobileTokenContext.tsx
  src/mobile-token/abtClientLogger.ts
  src/mobile-token/helpers.ts
  src/mobile-token/hooks/use-get-signed-token-query.tsx
  src/mobile-token/hooks/use-load-native-token-query.tsx
  src/mobile-token/hooks/use-preemptive-renew-token-mutation.tsx
  src/mobile-token/mobileTokenClient.ts
  src/mobile-token/tokenService.ts
  src/mobile-token/types.ts
  src/mobile-token/utils.ts
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx
  src/utils/bugsnag-utils.ts
  yarn.lock
Labels: App

#5032 refactor: Simplify button color selection
  src/components/button/Button.tsx
Labels: :wrench: Maintenance, App

#5048 fix: use correct value for travelright endDateTime
  src/modules/fare-contracts/sections/OrderDetailsSectionItem.tsx
Labels: App, :bug: Bug
