Repository AtB-AS/mittatb-app, pull requests merged in 2025-01, with the labels that each got.

#4899 fix: Some date tests failing after new year
  src/utils/__tests__/date.test.ts
  src/utils/date.ts
Labels: :wrench: Maintenance, App

#4908 feat: move live bus button beside LastPassedStop text
  src/travel-details-screens/DepartureDetailsScreenComponent.tsx
Labels: App, :iphone: 1.61

#4904 fix: Set BorderedInfoBox border color in same way as SectionItem separator color
  src/components/bordered-info-box/BorderedInfoBox.tsx
Labels: :people_holding_hands: Team initiative, App

#4839 fix: Wrong tests sometimes
  src/fare-contracts/__tests__/sort-fc-reservation-by-validity-creation.test.ts
  src/fare-contracts/utils.ts
Labels: App, :bug: Bug

#4921 bugfix: able to use map area between buttons
  src/components/map/Map.tsx
  src/components/map/hooks/use-control-styles.ts
Labels: App, :bug: Bug

#4917 fix: Adhere limitations in tariff zone selector
  src/purchase-selection/index.ts
  src/purchase-selection/use-selectable-tariff-zones.ts
  src/stacks-hierarchy/Root_PurchaseTariffZonesSearchByTextScreen/Root_PurchaseTariffZonesSearchByTextScreen.tsx
  src/tariff-zones-selector/TariffZonesSelectorMap.tsx
Labels: App, :bug: Bug

#4940 feat: Border radius circle on buttons
  src/components/button/Button.tsx
Labels: :people_holding_hands: Team initiative, App

#4945 feat: Slim border on small buttons
  src/components/button/Button.tsx
Labels: :people_holding_hands: Team initiative, App

#4949 feat: Remove button compact param
  src/components/button/Button.tsx
  src/components/empty-state/EmptyState.tsx
  src/components/map/components/BackArrow.tsx
  src/components/map/components/PositionArrow.tsx
  src/components/map/components/ScanButton.tsx
  src/components/map/components/bonus-program/BonusProgramMapButton.tsx
  src/components/map/components/external-realtime-map/ExternalRealtimeMapButton.tsx
  src/components/map/components/filter/MapFilter.tsx
  src/components/map/components/mobility/ShmoTesting.tsx
  src/favorites/FavoriteChips.tsx
  src/place-screen/components/DateSelection.tsx
  src/place-screen/components/StopPlaceAndQuaySelection.tsx
  src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/components/SendToOtherButton.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/CityZoneMessage.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx
  src/storybook/stories/Button.stories.tsx
  src/travel-details-screens/DepartureDetailsScreenComponent.tsx
  src/travel-details-screens/components/PaginatedDetailsHeader.tsx
Labels: :people_holding_hands: Team initiative, App

#4950 fix: Active button border color mismatch
  src/components/button/Button.tsx
Labels: :wrench: Maintenance, App

#4961 feat: update bootsplash color to match new design system
  env/atb/dev/.env
  env/atb/prodstaging/.env
  env/atb/staging/.env
  env/atb/store/.env
Labels: App

#4971 feat: use Zod for fare contact validation
  src/fare-contracts/FareContractInfoDetails.tsx
  src/fare-contracts/FareContractView.tsx
  src/fare-contracts/__tests__/sort-fc-reservation-by-validity-creation.test.ts
  src/fare-contracts/components/FareContractDescription.tsx
  src/fare-contracts/components/FareContractFromTo.tsx
  src/fare-contracts/components/ProductName.tsx
  src/fare-contracts/components/ValidTo.tsx
  src/fare-contracts/details/DetailsContent.tsx
  src/fare-contracts/details/OrderDetails.tsx
  src/fare-contracts/utils.ts
  src/notifications/use-has-fare-contract-with-activated-notification.tsx
  src/ticketing/TicketingContext.tsx
  src/ticketing/__tests__/farecontracts.test.ts
  src/ticketing/__tests__/get-availability-status.test.ts
  src/ticketing/__tests__/travelrights.test.ts
  src/ticketing/api.ts
  src/ticketing/get-availability-status.ts
  src/ticketing/types.ts
  src/ticketing/utils.ts
Labels: :wrench: Maintenance, App

#4967 test: Get apk from firebase app distribution
  .github/workflows/test-e2e-android.yml
  .github/workflows/test-performance-android.yml
  .github/workflows/test-visual-android.yml
  e2e/README.md
  e2e/conf/android.conf.local.firebase.ts
  e2e/firestore/get-appdistribution-apk.py
  e2e/firestore/requirements.txt
  e2e/package.json
  e2e/scripts/get-appcenter-apk.sh
  e2e/scripts/install-flashlight.sh
  e2e/scripts/run-flashlight-tests.sh
Labels: Test

#4972 fix: Fix wrongly visible zones
  src/fare-contracts/FareContractView.tsx
  src/fare-contracts/components/BorderedFromToBox.tsx
  src/fare-contracts/components/FareContractFromTo.tsx
  src/fare-contracts/components/HarborsFromTo.tsx
  src/fare-contracts/components/TravelInfoSectionItem.tsx
  src/fare-contracts/components/WithValidityLine.tsx
  src/fare-contracts/components/ZonesFromTo.tsx
Labels: :wrench: Maintenance, App

#4980 fix: update MoreCarsIndicator color
  src/mobility/components/CarPreviews.tsx
Labels: App, :bug: Bug
