Repository AtB-AS/mittatb-app, pull requests merged in 2025-09, with the labels that each got.

#5422 fix(spar): move SP&R button
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx
  src/translations/screens/Profile.ts
Labels: App, Smart🅿️ark&Ride

#5431 feat: add cancel button to consume and activate fc bottom sheet
  src/modules/fare-contracts/FareContractView.tsx
  src/modules/fare-contracts/components/ActivateNowBottomSheet.tsx
  src/modules/fare-contracts/components/ActivateNowSectionItem.tsx
  src/modules/fare-contracts/components/ConsumeCarnetBottomSheet.tsx
  src/translations/screens/FareContract.ts
Labels: :people_holding_hands: Team initiative, quickwin, App

#5433 feat: update appearance settings page
  src/components/text/ThemeText.tsx
  src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_AppearanceScreen.tsx
  src/theme/ThemeContext.tsx
  src/translations/screens/subscreens/AppearanceSettings.ts
Labels: :people_holding_hands: Team initiative, quickwin

#5443 feat: change wording from "start ticket" to "use ticket"
  src/translations/screens/FareContract.ts
Labels: :wrench: Maintenance, App, :iphone: 1.73

#5471 fix(spar): set stale time of vehicle registrations query
  src/modules/smart-park-and-ride/queries/use-get-vehicle-registrations-query.ts
Labels: App, Smart🅿️ark&Ride

#5423 test: e2e performance measure improvements
  e2e/scripts/run-flashlight-tests.sh
  e2e/test/flashlight/performanceMeasures.e2e.ts
  e2e/test/flashlight/performanceMeasures_departures.e2e.ts
  e2e/test/flashlight/performanceMeasures_map.e2e.ts
  e2e/test/flashlight/performanceMeasures_tickets.e2e.ts
  e2e/test/flashlight/performanceMeasures_travelsearch.e2e.ts
  e2e/test/pageobjects/map.page.ts
  e2e/test/pageobjects/ticket.buy.page.ts
  e2e/test/pageobjects/travelsearch.overview.page.ts
  e2e/test/specs/travelsearch.e2e.ts
  e2e/test/visualTests/specs/visual.travelsearch.e2e.ts
  src/screen-components/ticket-history/TicketHistoryScreenComponent.tsx
Labels: Test

#5475 test: e2e updates
  e2e/test/flashlight/performanceMeasures_tickets.e2e.ts
  e2e/test/pageobjects/purchase.overview.page.ts
  e2e/test/pageobjects/travelsearch.overview.page.ts
  e2e/test/specs/auth.0.cleanup.e2e.ts
  e2e/test/specs/auth.1.token.e2e.ts
  e2e/test/specs/auth.2.ticket.buy.e2e.ts
  e2e/test/specs/auth.3.ticket.e2e.ts
  e2e/test/specs/frontpage.e2e.ts
  e2e/test/specs/onboarding.e2e.ts
  e2e/test/specs/ticket.e2e.ts
  e2e/test/specs/travelsearch.e2e.ts
  e2e/test/specs/travelsearch.filter.e2e.ts
  e2e/test/utils/alert.helper.ts
Labels: Test
